### ISSUE TITLE
Increase allowed number of classical registers 

### ISSUE THREAD

**Issue by irfankhan10** [CQCL/pytket-qir#164]
When translating a pytket circuit with  more than 64 registers to a QIR program, there is a runtime error raised. This is due to a check performed during conversion. This check needs to accept circuits with greater than 64 registers. The H-Series device will support circuits containing up to 1000 classical registers.

https://github.com/CQCL/pytket-qir/blob/c86df01cdd2ceac31c49ed8280e2de4a6807dd49/pytket/qir/conversion/api.py#L109

**Comment by cqc-melf** [comment]
For me this works, can you give some more details about the issue?
I have tested this circuit:

```
    c = Circuit(0, 0, name="test_large_number_of_registers")
    for i in range(100):
        a = c.add_c_register(f"a_{i}", 10)
        c.add_c_setreg(32, a)

**Comment by cqc-alec** [comment]
The check in the code is for the maximum size of any register, not for the number of registers; I don't see a limit on that?

**Comment by irfankhan10** [comment]
Thanks for clarifying

**Comment by cqc-melf** [comment]
Can we close this then?
