### ISSUE TITLE
Consider removing `pyqir_0_6_compatibility` code

### ISSUE THREAD

**Issue by qartik** [CQCL/pytket-qir#65]
We explicitly require pyqir 0.8.2 at
https://github.com/CQCL/pytket-qir/blob/6b500b808831a545ada0670c5a2ae61ea7bcb227/setup.py#L49

So the bit below and other `pyqir_0_6_compatibility` code is unneeded.
https://github.com/CQCL/pytket-qir/blob/6b500b808831a545ada0670c5a2ae61ea7bcb227/pytket/qir/conversion/api.py#L88-L129

**Comment by qartik** [comment]
@cqc-melf any objections? I can go ahead and remove this dead code if you agree.

**Comment by cqc-melf** [comment]
We have added this in the past because we wanted to be compatible with older versions used on your side, if you don't need this it can be removed. Are you using now 0.8.x as well?

**Comment by qartik** [comment]
Yes, we are. There is no support for PyQIR below 0.8.2 in the backend compiler, AFAIK.

Just to confirm, @peter-campora do you think old versions are still in use and may require compatibility with pytket-qir?

Update (2023-08-15): We agreed that it can be removed.

**Comment by cqc-melf** [comment]
solved by #66
